// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxrgqcevvrenmxmfojnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4cmdxY2V2dnJlbm14bWZvam5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTAwNzEsImV4cCI6MjA2Mjg2NjA3MX0.kbfyH3spiM4UAFNwk9whWGBC9nbHtCUL6hrJnZVaXAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);